const trainingsData = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/l47k89dJsufir8",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/zIMDxfMY-Y7IYy",
    id: "0002",
    name: "45° side bend",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/7zGREfhRc7gyCn",
    id: "0003",
    name: "air bike",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/lnblMxR1OC4pnj",
    id: "1512",
    name: "all fours squad stretch",
    target: "quads",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/KqoI-hrakOziGQ",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/U0ZTz9kT74SAY4",
    id: "0007",
    name: "alternate lateral pulldown",
    target: "lats",
  },
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/0Mm6QGQ6XWZwQ4",
    id: "1368",
    name: "ankle circles",
    target: "calves",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/DszNhLCrj0BG3W",
    id: "3293",
    name: "archer pull up",
    target: "lats",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/qfbQus1-aIPkLW",
    id: "3294",
    name: "archer push up",
    target: "pectorals",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/McwGDJEVm5u4zY",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/QuQfBo1CBiDA5O",
    id: "2333",
    name: "arm slingers hanging straight legs",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/v-A1-FLPOJwqc0",
    id: "3214",
    name: "arms apart circular toe touch (male)",
    target: "glutes",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/yBPeNOgcazjiXw",
    id: "3204",
    name: "arms overhead full sit-up (male)",
    target: "abs",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/8J37wZKYIaeXRN",
    id: "0009",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://api.exercisedb.io/image/Q2TyCFlPQzKnsh",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://api.exercisedb.io/image/tDFpwAv3WY3YEY",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
  },
];

export default trainingsData;
